import { User } from './UserInterfaces';
import { Product } from './ProductInterfaces';
// Generated by https://quicktype.io

export interface OrdersResponse {
    ok: boolean;
    orders: Order[];
}

export interface Order {
    done?: boolean;
    _id?: string;
    client?: User;
    products: Products[];
    price?: number;
    created?: string;
    desc?: string;
    __v?: number;
    deliverDate?: string;
    employee?: User;
    ready?: boolean;
    employeeMarkReady?: User;
    readyDate?: Date;
}


export interface OrderToSend {
    products: ProductElement[];
    price?: number;
    desc?: string;
}

export interface ProductElement {
    _id?: string;
    unitPrice?: number;
    product: string;
    amount: number;
}

export interface Products {
    _id?: string;
    unitPrice?: number;
    product: Product;
    amount: number;
}



