// Generated by https://quicktype.io

export interface OrdersResponse {
    ok:     boolean;
    orders: Order[];
}

export interface Order {
    done?:         boolean;
    _id?:          string;
    client?:       string;
    products:     ProductElement[];
    price?:        number;
    created?:      string;
    __v?:          number;
    deliverDate?: string;
    employee?:    string;
}

export interface ProductElement {
    _id?:     string;
    product: string;
    amount:  number;
}


