
export interface Product {
    imgs?:      any[];
    available?: boolean;
    _id?:       string;
    name?:      string;
    price?:     number;
    user?:      string;
}
// Generated by https://quicktype.io

export interface ProductsResponse {
    ok:       boolean;
    products: Product[];
}


// Generated by https://quicktype.io

export interface productResponse {
    ok:      boolean;
    product: Product;
}

