export interface MeResponse {
    ok:   boolean;
    user: User;
}

export interface User {
    admin?:    boolean;
    employee?: boolean;
    imgsTemp?: any[];
    _id?:      string;
    name?:     string;
    mail?:     string;
    password?:string;
    __v?:      number;
}

export interface LoginResponse {
    ok:    boolean;
    token: string;
}


export interface UsersResponse {
    ok:    boolean;
    users: User[];
}
// Generated by https://quicktype.io

export interface UserByIDResponse {
    ok:   boolean;
    user: User;
}


export interface UpdateUserResponse {
    ok:    boolean;
    token: string;
    user:  User;
}
// Generated by https://quicktype.io

export interface ChangeRangeUserResponse {
    ok:   boolean;
    user: User;
}


